routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'superadmin', 'middleware' => 'auth'], function(){
	Route::get('/', 'MainController@index')->name('superadmin');
	Route::get('/categories', 'MainController@categories')->name('superadmin.categories');
	Route::get('/category/{id}', 'MainController@show_category');
});


Route::post('cart/ajax', 'FrontController@ajax_cart_update');
Route::post('wishlist/ajax', 'FrontController@ajax_wishlist_update');

Route::group(['prefix' => 'theme5'], function(){

	Route::get('/', 'Theme5\FrontController@index');
	Route::get('category/{slug}', 'Theme5\FrontController@get_products_by_category')->name('category.product.new5');
	Route::get('product/{slug}', 'Theme5\FrontController@view_product')->name('view.product.new5');
	Route::get('contact-us', 'Theme5\FrontController@contact');
	Route::get('privacy-policy', 'Theme5\FrontController@privacy_policy');
	Route::get('show-cart', 'Theme5\FrontController@cart_view')->name('cart.view5');
	Route::get('wish-list/{id}', 'Theme5\FrontController@wishlist')->middleware(['auth'])->name('wish5');
	Route::get('show-checkout', 'Theme5\FrontController@checkout_view')->name('checkout.view5');
	Route::post('search/product', 'Theme5\FrontController@search_product')->name('search.product5');
	Route::get('about-us', 'Theme5\FrontController@about_us');

});

Route::group(['prefix' => 'theme4'], function(){

	Route::get('/', 'Theme4\FrontController@index');
	Route::get('category/{slug}', 'Theme4\FrontController@get_products_by_category')->name('category.product.new4');
	Route::get('product/{slug}', 'Theme4\FrontController@view_product')->name('view.product.new4');
	Route::get('contact-us', 'Theme4\FrontController@contact');
	Route::get('privacy-policy', 'Theme4\FrontController@privacy_policy');
	Route::get('show-cart', 'Theme4\FrontController@cart_view')->name('cart.view4');
	Route::get('wish-list/{id}', 'Theme4\FrontController@wishlist')->middleware(['auth'])->name('wish4');
	Route::get('show-checkout', 'Theme4\FrontController@checkout_view')->name('checkout.view4');
	Route::post('search/product', 'Theme4\FrontController@search_product')->name('search.product4');
	Route::get('about-us', 'Theme4\FrontController@about_us');

});

Route::group(['prefix' => 'theme3'], function(){

	Route::get('/', 'Theme3\FrontController@index');
	Route::get('category/{slug}', 'Theme3\FrontController@get_products_by_category')->name('category.product.new3');
	Route::get('product/{slug}', 'Theme3\FrontController@view_product')->name('view.product.new3');
	Route::get('contact-us', 'Theme3\FrontController@contact');
	Route::get('privacy-policy', 'Theme3\FrontController@privacy_policy');
	Route::get('show-cart', 'Theme3\FrontController@cart_view')->name('cart.view3');
	Route::get('wish-list/{id}', 'Theme3\FrontController@wishlist')->middleware(['auth'])->name('wish3');
	Route::get('show-checkout', 'Theme3\FrontController@checkout_view')->name('checkout.view3');
	Route::post('search/product', 'Theme3\FrontController@search_product')->name('search.product3');

});

Route::group(['prefix' => 'theme2'], function(){

	Route::get('/', 'Theme2\FrontController@index');
	Route::get('privacy-policy', 'Theme2\FrontController@privacy_policy');
	Route::get('contact-us', 'Theme2\FrontController@contact');
	Route::get('more-products', 'Theme2\FrontController@get_more_products_new')->name('more.products.new2');
	Route::get('category/{slug}', 'Theme2\FrontController@get_products_by_category_new')->name('category.product.new2');
	Route::get('product/{slug}', 'Theme2\FrontController@view_product_new')->name('view.product.new2');
	// Route::resource('cart', 'Theme2\CartController');
	// Route::resource('checkout', 'Theme2\CheckoutController');
	Route::get('show-cart', 'Theme2\FrontController@cart_view')->name('cart.view2');
	Route::get('show-checkout', 'Theme2\FrontController@checkout_view')->name('checkout.view2');
	Route::get('login', 'Theme2\FrontController@login_new')->name('login.new2');
	Route::get('wish-list/{id}', 'Theme2\FrontController@wishlist')->middleware(['auth'])->name('wish2');
	Route::get('add-to-wish-list/{id}', 'Theme2\FrontController@wishlist_add')->middleware(['auth'])->name('wishlist.add2');
	Route::get('tag/{slug}', 'Theme2\FrontController@products_by_tag')->name('tag.products2');
	Route::post('search/product', 'Theme2\FrontController@search_product')->name('search.product2');
});

Route::group(['prefix' => 'theme1'], function(){

	Route::get('/', 'FrontController@index_new');
	Route::get('privacy-policy', 'FrontController@privacy_policy');
	Route::get('more-products', 'FrontController@get_more_products_new')->name('more.products.new');
	Route::get('category/{slug}', 'FrontController@get_products_by_category_new')->name('category.product.new');
	Route::get('product/{slug}', 'FrontController@view_product_new')->name('view.product.new');
	// Route::resource('cart', 'CartNewController');
	// Route::resource('checkout', 'CheckoutNewController');
	Route::get('show-cart', 'FrontController@cart_view')->name('cart.view');
	Route::get('show-checkout', 'FrontController@checkout_view')->name('checkout.view');
	Route::get('login', 'FrontController@login_new')->name('login.new');
	Route::get('wish-list/{id}', 'FrontController@wishlist')->middleware(['auth']);
	Route::get('add-to-wish-list/{id}', 'FrontController@wishlist_add')->middleware(['auth'])->name('wishlist.add');
	Route::get('tag/{slug}', 'FrontController@products_by_tag')->name('tag.products');
});

Route::get('/', 'FrontController@index_new');
Route::get('more-products', 'FrontController@get_more_products')->name('more.products');
Route::get('category/{slug}', 'FrontController@get_products_by_category')->name('category.product');
Route::get('product/{slug}', 'FrontController@view_product')->name('view.product');
Route::resource('cart', 'CartController');
Route::resource('checkout', 'CheckoutController');

Auth::routes();
Route::get('/order', function(){
	return view('boost_order');
});
Route::post('/boost-order/store', 'FrontController@boost_order_store')->name('boost.order.store'); 
Route::get('/', 'FrontController@index')->name('index');
Route::get('admin/boosted/orders', 'OrdersController@boosted_orders')->name('orders.boosted_orders');

Route::get('/suppliers', 'FrontController@get_all_suppliers')->name('suppliers');
Route::get('/privacy_policy', function(){
	return view('pages.privacy_policy');
});

Route::get('register', function(){
	return view('auth.login');
})->name('register');
Route::get('supplier', function(){
	return view('pages.suppliers.index')->with('users', App\User::orderBy('id','desc')->get());
});
Route::get('supplier/{id}', function(){
	return view('pages.suppliers.index')->with('users', App\User::orderBy('id','desc')->get());
});
Route::get('category', function(){
	return redirect()->route('index');
});
Route::get('product', function(){
	return redirect()->route('index');
});

Route::get('supplier/{id}/{name}', 'FrontController@view_supplier')->name('view.supplier');
Route::post('search/product', 'FrontController@search_product')->name('search.product');
Route::post('user_reviews', 'FrontController@add_review')->name('add.review');
Route::post('product/review', 'FrontController@insert_product_review')->name('product.review');
Route::post('product/by/location', 'FrontController@get_products_by_location')->name('product.location');

Route::get('Featured-Products', 'FrontController@get_featured_products')->name('featured.products');

//ORDERS
Route::post('/order/store', 'OrdersController@store_order')->name('order.store');

Route::get('/ajax/set_session', 'FrontController@set_session_product_id');

Route::group([
				'prefix' => 'admin',
				'middleware' => 'auth',
			],
			function(){
				Route::get('/', 'ProductController@index')->name('dashboard');
				Route::resource('/products', 'ProductController');
				Route::resource('/categories', 'CategoryController');
				Route::resource('/profile', 'ProfileController');
				Route::resource('/users', 'UserController');
				Route::resource('/photos', 'PhotosController');
        		Route::resource('/videos', 'VideosController');
				Route::post('/make/featured', 'AdminController@make_featured')->name('make.featured');
				Route::post('/unmake/featured', 'AdminController@unmake_featured')->name('unmake.featured');
		        Route::get('featured', 'AdminController@featured')->name('featured.index');
		        Route::resource('orders', 'OrdersController');
		        Route::resource('reviews', 'ReviewsController');
		        Route::get('/showorders', 'AdminController@get_all_orders')->name('orders.showall');
		        Route::get('suspend/users', 'AdminController@suspend_users')->name('users.suspend');
		        Route::post('suspend/users', 'AdminController@make_user_suspend')->name('make.users.suspend');
		        Route::resource('/managesuppliers', 'SupplierController', ['except' => ['show', 'index', 'destroy']]);
		        Route::resource('sliders', 'SlidersController');
		        Route::resource('tags', 'TagsController');
		        Route::get('product/removeImage/{id}', 'ProductController@remove_image')->name('remove.image');
		        Route::resource('sitesettings', 'SettingsController');
			});

Route::get('login/facebook/', 'Auth\LoginController@redirectToFacebookProvider')->name('facebook.login');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

resources/views/admin/boost_orders.blade.php
@extends('layouts.main')

@section ('content')

<div class="container" style="padding: 50px 0px">
	<h4>Admin Panel</h4>
	<div class="row">
		<div class="col-md-3">
			@include('admin.sidebar')
		</div>
		<div class="col-md-9">
			<div class="card">
				<div class="card-body">
					<h4 class="mb-3"><i class="fa fa-rocket" style="color: black" aria-hidden="true"></i> &nbsp;Orders:</h4>
					<table id="example" class="table table-condensed table-bordered">
						<thead>
							<tr>
								<th>Name:</th>
								<th>Mobile:</th>
								<th>Address:</th>
								<th>Message:</th>
								<th>Created at:</th>	
							</tr>
						</thead>
						<tbody>
							@foreach ($orders as $o)
							<tr>
								<td> {{ $o->name }} </td>
								<td> {{ $o->phone }} </td>
								<td> {{ $o->address }} </td>
								<td> {{ $o->message }} </td>
								<td> {{ $o->created_at }} </td>						
							</tr>
							@endforeach() 
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/admin/categories.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="padding: 25px 15px">
    <h4>Admin Panel</h4>
    <div class="row">
        <div class="col-md-3">
            @include('admin.sidebar')
        </div>
        <div class="col-md-9">
            <div class="card">
              <div class="card-body">
                <div class="card-header">
                    <strong>Manage Categories:</strong>
                    <a href="{{ route('categories.create') }}" class="btn btn-info btn-sm">Add New <i class="fa fa-plus"></i></a>
                </div>
                <hr>
                <div class="card-text">
                    <div class="row">
                        <div class="col-md-12">
                            <table id="example" class="table table-bordered table-condensed">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Slug</th>
                                        <th>Is Parent?</th>
                                        <th>Parent Category</th>
                                        <th>#</th>
                                        <th>Edit</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($categories as $cat)
                                    <tr>
                                        <td>{{ $cat->name }}</td>
                                        <td>{{ $cat->slug }}</td>
                                        <td>
                                            {!! $cat->parent ? '<i class="fa fa-check" aria-hidden="true"></i>' : '-' !!}
                                        </td>
                                        <td>{{ $cat->parentID }}</td>
                                        <td>{{ $cat->products()->count() }}</td>
                                        <td>
                                            <a href="{{ route('categories.edit', $cat->id) }}" class="btn btn-sm btn-danger">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
              </div>
        </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/featured.blade.php
@extends('layouts.app')

@section ('content')

<div class="container" style="padding: 25px 15px">
	<h4>Admin Panel</h4>
	<div class="row">
				<div class="col-md-3">
					@include('admin.sidebar')
				</div>
				<div class="col-md-9">
					<div class="card">
						<div class="card-body">
							<h4 class="mb-3">Manage Products</h4>
							<table class="display table table-condensed table-bordered" style="width: 100%">
								<thead>
									<tr>
										<th>Title</th>
										<th>Supplier</th>
                    					<th>Created</th>
										<th>Feature</th>
										<th>Unfeature</th>
									</tr>
								</thead>
								<tbody>
								@foreach (App\Product::orderBy('id','desc')->get() as $p)
									<tr>
										<td>{{ $p->title }}</td>
										<td>{{ $p->user->name }}</td>
										@php  $d = strtotime($p->updated_at); @endphp
										<td>{{ date( 'Y-M-d' , $d) }}</td>

										<td>
											<form class="feat-class" action="{{route('make.featured')}}" method="post">
											{{csrf_field()}}
											<input class="chk" type="checkbox" name="featured" value="{{$p->id}}" {{$p->featured==1 ? 'checked' : ''}}>
											
											<noscript><input type="submit"></noscript>
											</form>
										</td>

										<td>
											<form action="{{route('unmake.featured')}}" method="post">
											{{csrf_field()}}
											<input type="hidden" name="notfeatured" value="{{$p->id}}" >
											
											<input type="submit" value="x" 
											style="border: none;color: white;background: #ff0000d1;cursor: pointer;height: 25px;padding: 0px 8px;">
											</form>
										</td>
									</tr>
								@endforeach
								</tbody>
							</table>

						</div>
					</div>
				</div>
	</div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section ('content')

<div class="container" style="padding: 25px 15px">
	<h4>Admin Panel</h4>
	<div class="row">
				<div class="col-md-3">
					@include('admin.sidebar')
				</div>
				<div class="col-md-9">
					<div class="card">
						<div class="card-body">
							<h4 class="mb-3">Manage Users</h4>
							<table id="example" class="table table-condensed table-bordered">
								<thead>
									<tr>
										<th>Name</th>
										<th>Email</th>
										<th>Role</th>
										<th>Active/Suspended</th>
									</tr>
								</thead>
								<tbody>
								@foreach ($users as $user)
									<tr>
										<td>{{ $user->username }}</td>
										<td>{{ $user->email }}</td>
										<td>{{ $user->roles->first()->role }}</td>
										<td>{{ $user->suspend == 0 ? 'Active' : 'Suspended' }}</td>
									</tr>
								@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
	</div>
</div>

@endsection

resources/views/admin/orders.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="padding: 25px 15px">
    <h5>Admin Panel</h5>
    <div class="row">
    <div class="col-md-3">
        @include('admin.sidebar')
    </div>
    <div class="col-md-9">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Products</h5>
            <p class="card-text">
                <table id="example" class="table table-condensed table-responsive">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Item</th>
                            <th>Client Name</th>
                            <th>Email</th>
                            <th>Phone No.</th>
                            <th>Delivery Address</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($orders as $o)
                        @if($o->product)
                        <?php 
                            $slug = explode(' ', $o->product->title);
                            $slug = implode('-', $slug); 
                        ?>
                          
                        <tr>
                            <td> <img src="{{asset('uploads/products/thumbnails/' . $o->product->image )}}" alt="Alt" height="50" width="50"> </td>
                            <td>{{ $o->product->title }}</td>
                            <td>{{ $o->name }}</td>
                            <td>{{ $o->user_email }}</td>
                            <td>{{ $o->phone }}</td>
                            <td>{{ $o->address }}</td>
                        </tr>
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </p>
          </div>
        </div>
    </div>
    </div>
</div>
@endsection

resources/views/admin/products.blade.php
@extends('layouts.app')

@section ('content')

<div class="container" style="padding: 25px 15px">
	<h4>Admin Panel</h4>
	<div class="row">
				<div class="col-md-3">
					@include('admin.sidebar')
				</div>
				<div class="col-md-9">
					<div class="card">
						<div class="card-body">

							<h4 class="mb-3">Manage Products</h4>
							<table id="example" class="display table table-condensed table-bordered" style="width: 100%">
								<thead>
									<tr>
										<th></th>
										<th>Title</th>
										<th>Supplier</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
								@foreach (App\Product::orderBy('id','desc')->get() as $p)
									<tr>
										<td>
											<img src="{{asset('uploads/products/thumbnails/'.$p->featuredImage)}}" alt="Image" height="50" width="80">
										</td>
										<td>{{ $p->productName }}</td>
										<td>{!! $p->user->supplier ? $p->user->supplier->detail : '<p style="color:red">Profile Not added</p>' !!}</td>
										@php  $d = strtotime($p->updated_at); @endphp
										<!-- <td>{{ date( 'Y-M-d' , $d) }}</td> -->
										<td>
											<form action="{{route('products.destroy', $p->id)}}" method="post">
												{{ csrf_field() }}
												{{ method_field('delete') }}
												<input type="submit" class="delete-btn" value="Delete">
											</form>
										</td>
									</tr>
								@endforeach
								</tbody>
							</table>

						</div>
					</div>
				</div>
	</div>
</div>

@endsection

resources/views/admin/sidebar.blade.php
<ul class="list-group">
    <li class="list-group-item">
        <a href="{{ route('sitesettings.index') }}">Site Settings</a>
    </li>

    <li class="list-group-item">
        <a href="{{ route('products.index') }}">Manage Products</a>
    </li>
    <li class="list-group-item">
        <a href="{{ route('users.index') }}">Manage Users</a>
    </li>
    <li class="list-group-item">
        <a href="{{ route('categories.index') }}">Manage Categories</a>
    </li>
    <li class="list-group-item">
        <a href="{{ route('tags.index') }}">Manage Tags</a>
    </li>
    <li class="list-group-item">
      <a href="{{ route('featured.index') }}">Featured Products</a>
    </li>
    <li class="list-group-item">
        <a href="{{ route('sliders.index') }}">App Sliders</a>
    </li>
    <li class="list-group-item">
      <a href="{{ route('orders.showall') }}">See all Product Orders</a>
    </li>
    <li class="list-group-item">
      <a href="{{ route('orders.boosted_orders') }}"><i class="fa fa-rocket" style="color: black" aria-hidden="true"></i> &nbsp;Orders</a>
    </li>
    <li class="list-group-item">
      <a href="{{ route('users.suspend') }}">Suspend Users</a>
    </li>
</ul>

resources/views/admin/suspend_users.blade.php
@extends('layouts.app')

@section ('content')

<div class="container" style="padding: 25px 15px">
	<h4>Admin Panel</h4>
	<div class="row">
				<div class="col-md-3">
					@include('admin.sidebar')
				</div>
        <div class="col-md-9">
          <div class="card">
						<div class="card-body">

							<h4 class="mb-3">Suspend/Block Users</h4>

              <form class="form" action="{{route('make.users.suspend')}}" method="post">
                {{csrf_field()}}
                <label><b>Suppliers:</b></label><br>

                <div class="row">
                @foreach($users as $user)
                  @if($user->profile)
                    <div class="col-md-4">
                      <input type="checkbox" name="user_ids[]" value="{{ $user->id }}" {{ $user->suspend == 1 ? 'checked' : '' }}>
                       {{ $user->email }}
                    </div>
                  @endif
                @endforeach
                </div>
                <hr>
                <input type="submit" name="submit" value="Change" class="btn btn-warning">
              </form>

            </div>
          </div>
        </div>
  </div>
</div>

@endsection